testsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView # new
from django.contrib.auth import views as auth_views

from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),	
    path('', include('users.urls')),

]

users/urls.py
from django.urls import path, include
from django.conf import settings
from .views import *
from django.conf.urls.static import static
from . import views

app_name="users"

urlpatterns = [
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('',views.login_view,name='home'),
    path('course/', CourseView.as_view(), name='course'),
    path('course-create/', CourseCreateView.as_view(), name='course-create'),
    path('avialble_course/', AvailableCourseView.as_view(), name='available_course'),
    path('<int:id>/course-view/', course_single, name='course-view'),
    path('<int:id>/autograde-view/', GradeView, name='autograde-view'),
    path('login/', views.login_view, name='login'),
    #path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('student/', views.student, name='student'),
    path('instructor/', views.instructor, name='instructor'),
    path('assignment_create/<int:id>',AssignmentCreateView.as_view() , name='assignment_create'),

    path('assignment/<int:id>', AssignmentView.as_view(), name='assignment-list'),
    path("password_change/", views.password_change, name="password_change"),
    path('update/', EditProfileView.as_view(), name='profile-update'),
    path('join/',views.join_course,name='join_course'),
    path('reassignment_submission/<int:id>', ReAssignmentSubmissionView.as_view(), name='reassignment_submission'),
    path('assignment_submission/<int:id>', AssignmentSubmissionView.as_view(), name='assignment_submission'),
    path('gradeassignment_submission/<int:id>', GradeAssignmentSubmissionView.as_view(), name='gradeassignment_submission'),
    path('assignment-submission-list/<int:id>', AssignmentSubmissionListView.as_view(), name='assignment-submission-list'),
    path('gradeassignment-submission-list/<int:id>', AssignmentSubmissionGradeListView.as_view(), name='gradeassignment-submission-list'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/assignment_create.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block title %} Assignment Create {% endblock %}

{% block content %}

    <section class="dentist-area section-padding-40-0">
<div class="container">

<div class="row justify-content-center">

                <div class="col-lg-5 mb-5 mb-lg-0">
                    <center> <h3> Create Assignment </h3></center>
                          <br/>
                    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}

                        {{ form|bootstrap }}

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Create" class="btn btn-primary btn-md text-white">
                            </div>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

templates/assignment_submission.html
 {% extends 'base.html' %}

{% load bootstrap %}

{% block title %} Assignment Submission {% endblock %}

{% block content %}

    <section class="dentist-area section-padding-40-0">
<div class="container">

<div class="row justify-content-center">

                <div class="col-lg-5 mb-5 mb-lg-0">
                    <center> <h3> Submit Assignment </h3></center>
                          <br/>
                    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}

                        {{ form|bootstrap }}

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Submit" class="btn btn-primary btn-md text-white">
                            </div>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

templates/assignments.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Assignments{% endblock %}

{% block content %}


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<link rel="stylesheet" href="{% static 'css/viewcourse.css'%}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


            {% if request.user.is_authenticated and request.user.role == 'instructor' %}
            <div class="topnav" id="myTopnav">
                <a href="{%url 'users:instructor'%}" class="active">Home</a>
                <a href="{% url 'users:course' %}">View Courses</a>
                <a href="{% url 'users:logout' %}">Logout</a>
                <a href="javascript:void(0);" class="icon" onclick="myFunction()">
                <i class="fa fa-bars"></i>
                </a>
                </div>       
                
                <div class="sidebar">
                
                        <a class="active" href="{% url 'users:assignment-list' course.id %}">{{request.user.first_name}}  {{request.user.last_name }}</a>
                        <a class="active"href="{% url 'users:assignment-list' course.id %}">{{request.user.username}}</a>
                        <a href="{% url 'users:course-view' course.id %}">Back To Course</a>
                      </div>
                    <br>
                    <br><br><br>
                    <strong><h1 class="head2">Assignments</h1></strong>
                
                    <div class="container1">
                        
                        <div class="col-12 col-sm-6 col-md-10">



                {% for foo in assignment %}
                
                    <hr/><div class="container2">
                    <h3><strong> {{ foo.assignment_name }}  </strong><a href="{% url 'users:assignment-submission-list' foo.id %}" class="button">Assignment Submissions</a></h3>
                    
                    <h3> Question Content :</h3> <h4>{{ foo.question_content }} </h4>
                 
                    <h3> Problem Statement Link :<a href = "/users/media/{{ foo.related_file }}"> Here </a> </h3>
                   
                    <h3> Maximum Marks : {{ foo.assignment_marks }} </h3>    
                    <h3> Deadline:</h3><h4> {{ foo.deadline }} </h4>
                    <h3> Valid extensions of submission file :</h3> <h4>{{ foo.extensions }} </h4>    
                    <h3> File directory structure text file :<a href = "/users/media/{{ foo.file_directory_structure_textfile }}"> Here </a> </h3>    
                    <h3> Autograder script file :<a href = "/users/media/{{ foo.autograde_script_zipfile }}"> Here </a> </h3>
                </div>    <hr/>
                
                    
                    <br>

                {% endfor %}
          

                


        

            {% else %}

            <div class="topnav" id="myTopnav">
                <a href="{%url 'users:student'%}" class="active">Home</a>
                <a href="{% url 'users:course' %}">View Courses</a>
                <a href="{% url 'users:logout' %}">Logout</a>
                <a href="javascript:void(0);" class="icon" onclick="myFunction()">
                <i class="fa fa-bars"></i>
                </a>
                </div>       
                
                <div class="sidebar">
                
                        <a class="active" href="{% url 'users:assignment-list' course.id %}">{{request.user.first_name}}  {{request.user.last_name }}</a>
                        <a class="active"href="{% url 'users:assignment-list' course.id %}">{{request.user.username}}</a>
                        <a href="{% url 'users:course-view' course.id %}">Back To Course</a>
                      </div>
                    <br><br><br><br><br><br>
                    <strong><h1 class="head2">Assignments</h1></strong>


                    <div class="container1">
                        
                        <div class="col-12 col-sm-6 col-md-10">

                {% for foo in assignment %}
                    <hr/><div class="container2">
                    <h3><strong> {{ foo.assignment_name }}  </strong></h3>                  
                    <h3>Question Content :</h3> <h4>{{ foo.question_content }} </h4>
                    <h3>Question File :<a href = "/users/media/{{ foo.related_file }}"> link</a>  </h3>   
                    <h3> Problem Statement Link:<a href = "/users/media/{{ foo.related_file }}"> Here </a> </h3>
                    <h3> Maximum Marks: {{ foo.assignment_marks }} </h3>    
                    <h3> Deadline: <small> {{ foo.deadline }} </small></h3>
                    <h3> Valid extensions of submission file: {{ foo.extensions }}</h3>    
                    <h3> File directory structure text file:<a href = "/users/media/{{ foo.file_directory_structure_textfile }}"> Here </a> </h3>    
                          <br>
                                            
                      <br>
                      
                    <script>
                    var x=0;
                    var datetime = new Date(); 
                    console.log(datetime);
                    document.getElementById("time").textContent = datetime;
                    var time = new Date();
                    var date = time.getFullYear()+'-'+(time.getMonth()+1)+'-'+time.getDate(); 
                    </script> 
                      <p>{{date}}</p>       
                      {% if date > foo.deadline %}
                             <p>Deadline completed</p>
                      {% endif %}
                      {% for foo1 in assignment_submission %}
                        {% if foo1.user.username == request.user.username and foo1.no == foo.id %}
                            <h4> Assignment Submitted </h4>
                            <div class="btn-group">
                                <button id="1"> <a href="{% url 'users:assignment-submission-list' foo.id %}" >View Submission</a></button>
                           
                                <button id='2'> <a href="{% url 'users:reassignment_submission' foo.id %}">Resubmit Assignment</a></button>
                         
                                <button id="3"><a href="{% url 'users:autograde-view' foo1.id %}">Automatic Grade</a></button>
                                <button id="4"><a href="{% url 'users:gradeassignment-submission-list' foo.id %}">Manual Grade</a></button>
                        </div>
                            {% endif %}
                      
                    {% endfor %}
                        
                         
                          
                          
                          <h4><a href="{% url 'users:assignment_submission' foo.id %}">Submit Assignment</a></h4>
                        
                        </div>    <hr/> 
                {% endfor %}

            {% endif %}
            <br/>
        </div>

    </div>

{% endblock %}

templates/autograde.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Courses{% endblock %}
{% block content %}

        <div class="container">

        <div class="col-12 col-sm-6 col-md-10">
            <h3><strong>{{ assignment_submission.feedback }}  </strong></h3>
        </div>

    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>User Authentication System</title>
    
    {% block style %}
    {% endblock style %}
</head>
<body>
    <div class="container">
        {% include 'includes/messaging.html' %}
        {% block content %}
        {% endblock content %}
    </div> 
</body>
</html>

templates/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>User Authentication System</title>
    
    {% block style %}
    {% endblock style %}
</head>
<body>
    <div class="container">
    {% include 'users/includes/messaging.html' %}
        {% block content %}
        {% endblock content %}
    </div> 
</body>
</html>

templates/course_create.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block title %} Course Create {% endblock %}

{% block content %}

    <section class="dentist-area section-padding-40-0">
<div class="container">

<div class="row justify-content-center">

                <div class="col-lg-5 mb-5 mb-lg-0">
                    <center> <h3>Create Course</h3></center>

                    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}

                        {{ form|bootstrap }}

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Create" class="btn btn-primary btn-md text-white">
                            </div>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

templates/courses.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Courses{% endblock %}


{% block content %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <link rel="stylesheet" href="{% static 'css/courses.css'%}">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



{% if request.user.is_authenticated and request.user.role == 'instructor' %}
<div class="topnav" id="myTopnav">
  <a href="{%url 'users:instructor'%}">Home</a>
  <a href="{% url 'users:course' %}"  class="active">{{request.user.first_name}}  {{request.user.last_name }}</a>
  <a href="{% url 'users:logout' %}">Logout</a>
  <a href="javascript:void(0);" class="icon" onclick="myFunction()">
    <i class="fa fa-bars"></i>
  </a>
</div>
   
    <div class="container">


      <div class="row">

        <!-- Section Heading -->
        <br>
        <br>
          <div class="col-12">
          <div class="section-heading text-center">

             
            <h2> Courses</h2>
            <div class="line"></div>
          </div>
        </div>
      </div>
      <br>
      <br> 
      <div class="row">
          {% for course in course %}
         {% if request.user.first_name == course.teacher_name %} 
        <!-- Single Dentist Area -->
        <div class="col-12 col-sm-6 col-md-4">

          <div class="single-dentist-area mb-100">
            <img  style="height: 300px; width: 350px " src="{{ course.course_image.url }}" alt="">
            <!-- Dentist Content -->
            <div class="dentist-content">
              <!-- Social Info -->
              <div class="dentist-social-info">

              </div>
              <!-- Dentist Info -->
              <div class="dentist-info bg-gradient-overlay">
                  <h4>{{ course.course_name }} |  <a href="{% url 'users:course-view' course.id %}"> VIEW COURSE</a> </h4>
                <h4>{{ course.teacher_name }} </h4>
                <h4>Course Code: {{ course.course_code }} </h4>


              </div>
            </div>
          </div>
        </div>
       {% endif %} 
      {% endfor %}

      </div>
    </div>
    
{% endif %}


{% if request.user.is_authenticated and request.user.role == 'student' %}
<div class="topnav" id="myTopnav">
  <a href="{%url 'users:student'%}" >Home</a>
  <a href="{% url 'users:course' %}">{{request.user.first_name}}  {{request.user.last_name }}</a>
  <a href="{% url 'users:logout' %}">Logout</a>
  <a href="javascript:void(0);" class="icon" onclick="myFunction()">
    <i class="fa fa-bars"></i>
  </a>
</div>

    <div class="container">


      <div class="row">

        <!-- Section Heading -->
        <div class="col-12">
          <div class="section-heading text-center">

            <br>
            <h2>Courses</h2>
            <br>
          </div>
        </div>
      </div>

      <div class="row">
          {% for course in request.user.courses.all %}
        <!-- Single Dentist Area -->
        <div class="col-12 col-sm-6 col-md-4">

          <div class="single-dentist-area mb-100">
            <img  style="height: 300px; width: 350px " src="{{ course.course_image.url }}" alt="">
            <!-- Dentist Content -->
            <div class="dentist-content">
              <!-- Social Info -->
              <div class="dentist-social-info">

              </div>
              <!-- Dentist Info -->
              <div class="dentist-info bg-gradient-overlay">
                  <h4>{{ course.course_name }} |  <a href="{% url 'users:course-view' course.id %}">VIEW COURSE</a> </h4>
                <h4>{{ course.teacher_name }} </h4>


              </div>
            </div>
          </div>
        </div>
      {% endfor %}

      </div>
    </div>
{% endif %}
{% endblock %}

templates/edit_profile.html
{% load static %}
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>HTML5 Login Form with validation Example</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <link rel="stylesheet" href="{% static 'css/login.css'%}">

</head>
<body>
<!-- partial:index.partial.html -->
<div id="login-form-wrap">
  <h2>Edit Profile</h2>
  <form id="login-form" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" id="login" value="Update Profile">
  </form>
</div><!--login-form-wrap-->
<!-- partial -->
  
</body>
</html>

templates/gradeassignment_submission.html
 {% extends 'base.html' %}

{% load bootstrap %}

{% block title %} Grade Assignment {% endblock %}

{% block content %}

    <section class="dentist-area section-padding-40-0">
<div class="container">

<div class="row justify-content-center">

                <div class="col-lg-5 mb-5 mb-lg-0">
                    <center> <h3> Submit Grade </h3></center>
                          <br/>
                    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}

                        {{ form|bootstrap }}

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Submit" class="btn btn-primary btn-md text-white">
                            </div>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

templates/login.html
{% load static %}
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>HTML5 Login Form with validation Example</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <link rel="stylesheet" href="{% static 'css/login.css'%}">

</head>
<body>
<!-- partial:index.partial.html -->
<br><br>
<br><br>
<div id="login-form-wrap">
  
  <h2><strong>Login</strong></h2>
  
  <form id="login-form" action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
        <p>{{ field.label }}: <br> {{ field }}</p>
    {% endfor %}
    <input type="submit" id="login" value="Login">
    </p>
  </form>
  <div id="create-account-wrap">
    <h3>Don't have an account? <a href="{% url 'users:signup' %}">Sign Up</a><h3>
  </div><!--create-account-wrap-->
</div><!--login-form-wrap-->
<!-- partial -->
  
</body>
</html>

templates/password_reset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
  	 	<h2>Reset Password</h2><hr>
		<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-outline-info" type="submit">Send email</button>
        </
  	</div>
{% endblock %}>

templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <div class="alert alert-success" role="alert">
        <h3 style="text-align: center;">Sign Up</h3>
    </div>
    <br>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <p> 
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
        </p>
        {% endfor %}
        <button type="submit">Sign up</button>
    </form>
{% endblock content%}

templates/student.html
{% load static %}
{% if user.is_authenticated %}
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <link rel="stylesheet" href="{% static 'css/instructor.css'%}">
    <div class="alert alert-success" role="alert">
        
         <div class="sidebar">
        <a class="active" href="{% url 'users:password_change' %}">Change Password</a>
        <a href="{% url 'users:profile-update' %}">Edit Profile: </a>
        <a href="{% url 'users:logout' %}">logout</a>
      </div>
        
        <div class="box">
          <h1>Welcome {{ user.username }}!</h1>
          <h2>  This is a Student page</h2>
        <a href="{% url 'users:course' %}">Courses</a>
        <br>
        <a href="{% url 'users:join_course' %}">Join Course</a>
        <br>
        <a href="{% url 'users:available_course' %}">Available Courses</a>
        </div>
    </div>
{% else %}
    <div style="text-align: center;" class="alert alert-success" role="alert">
        <h3 style="text-align: center;">WELCOME!!</h3>
        <a href="{% url 'users:signup' %}">Signup</a>
        <a href="{% url 'users:login' %}">Login</a>
    </div>
{% endif %}